spring:
  application:
    name: Factory_Test_Demo
  config:
    import: optional:classpath:application-local.yaml
  sql:
    init:
      mode: always
      schema-locations: classpath:db/schema.sql
      continue-on-error: false
  mail:
    host: smtp.qq.com
    port: 465
    protocol: smtp
    ssl:
      enabled: true
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
            trust: smtp.qq.com
          from: ${spring.mail.username}
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: FactoryTestDemoHikariCP
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-timeout: 30000
      validation-timeout: 5000
      keepalive-time: 300000
  output:
    ansi:
      enabled: always

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false

server:
  port: 8081

logging:
  level:
    com:
      zx:
        auth:
          mapper: debug
          service: info
          controller: info
